interface Child {
  id: string
  firstName: string
  lastName: string
  birthdate: string // Format: YYYY-MM-DD
  enrollmentDate: string // Format: YYYY-MM-DD
  gradeLevel: number
  healthStatus: string
  guardianName: string
  guardianContact: string
  address: string
  comments?: string
  lastCheckupDate?: string
}

export const dummyChildren: Child[] = [
  {
    id: '1',
    firstName: 'Aina',
    lastName: 'Rakoto',
    birthdate: '2015-04-10',
    enrollmentDate: '2022-09-05',
    gradeLevel: 3,
    healthStatus: 'Good',
    guardianName: 'Ravelo Andriana',
    guardianContact: '+261 34 567 890',
    address: 'Antananarivo, Madagascar',
    comments: 'Excels in reading activities',
    lastCheckupDate: '2023-10-12',
  },
  {
    id: '2',
    firstName: 'Tiana',
    lastName: 'Rasolofoniaina',
    birthdate: '2014-11-25',
    enrollmentDate: '2022-09-05',
    gradeLevel: 4,
    healthStatus: 'Underweight',
    guardianName: 'Vola Rajo',
    guardianContact: '+261 34 123 456',
    address: 'Antsirabe, Madagascar',
    comments: 'Needs nutritional support',
    lastCheckupDate: '2023-10-20',
  },
  {
    id: '3',
    firstName: 'Miora',
    lastName: 'Andriamihaja',
    birthdate: '2016-01-18',
    enrollmentDate: '2023-01-12',
    gradeLevel: 2,
    healthStatus: 'Moderate',
    guardianName: 'Solofo Rasoanaivo',
    guardianContact: '+261 33 789 012',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Recently joined, adjusting well',
    lastCheckupDate: '2023-09-28',
  },
  {
    id: '4',
    firstName: 'Rivo',
    lastName: 'Andriamanga',
    birthdate: '2013-05-15',
    enrollmentDate: '2021-09-05',
    gradeLevel: 5,
    healthStatus: 'Good',
    guardianName: 'Henintsoa Andriamanga',
    guardianContact: '+261 34 567 123',
    address: 'Toamasina, Madagascar',
    comments: 'Participates actively in classes',
    lastCheckupDate: '2023-08-25',
  },
  {
    id: '5',
    firstName: 'Soa',
    lastName: 'Rafalimanana',
    birthdate: '2017-03-10',
    enrollmentDate: '2023-03-15',
    gradeLevel: 1,
    healthStatus: 'Good',
    guardianName: 'Feno Rafalimanana',
    guardianContact: '+261 34 897 234',
    address: 'Mahajanga, Madagascar',
    comments: 'Very curious and observant',
    lastCheckupDate: '2023-07-12',
  },
  {
    id: '6',
    firstName: 'Faly',
    lastName: 'Andriatsiferana',
    birthdate: '2012-09-22',
    enrollmentDate: '2021-10-05',
    gradeLevel: 6,
    healthStatus: 'Moderate',
    guardianName: 'Rado Andriatsiferana',
    guardianContact: '+261 33 123 678',
    address: 'Antsiranana, Madagascar',
    comments: 'Enjoys outdoor activities',
    lastCheckupDate: '2023-08-05',
  },
  {
    id: '7',
    firstName: 'Lalao',
    lastName: 'Rafidison',
    birthdate: '2016-11-20',
    enrollmentDate: '2023-01-22',
    gradeLevel: 2,
    healthStatus: 'Good',
    guardianName: 'Tiana Rafidison',
    guardianContact: '+261 32 564 123',
    address: 'Antananarivo, Madagascar',
    comments: 'Very sociable with other kids',
    lastCheckupDate: '2023-09-12',
  },
  {
    id: '8',
    firstName: 'Fara',
    lastName: 'Rabenarivo',
    birthdate: '2015-07-05',
    enrollmentDate: '2022-09-15',
    gradeLevel: 3,
    healthStatus: 'Underweight',
    guardianName: 'Zo Rabenarivo',
    guardianContact: '+261 33 999 876',
    address: 'Antsirabe, Madagascar',
    comments: 'Requires regular health checkups',
    lastCheckupDate: '2023-10-10',
  },
  {
    id: '9',
    firstName: 'Hery',
    lastName: 'Andrianjafy',
    birthdate: '2014-02-14',
    enrollmentDate: '2021-04-18',
    gradeLevel: 4,
    healthStatus: 'Good',
    guardianName: 'Hanitra Andrianjafy',
    guardianContact: '+261 34 678 987',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Has strong math skills',
    lastCheckupDate: '2023-10-18',
  },
  {
    id: '10',
    firstName: 'Soamiely',
    lastName: 'Randriambololona',
    birthdate: '2013-12-29',
    enrollmentDate: '2021-09-10',
    gradeLevel: 5,
    healthStatus: 'Good',
    guardianName: 'Faniry Randriambololona',
    guardianContact: '+261 34 123 456',
    address: 'Toliara, Madagascar',
    comments: 'Shows potential in art',
    lastCheckupDate: '2023-10-05',
  },
  // Continue adding similar objects up to 40 entries
  {
    id: '11',
    firstName: 'Tsiry',
    lastName: 'Rasoanaivo',
    birthdate: '2017-08-16',
    enrollmentDate: '2023-03-10',
    gradeLevel: 1,
    healthStatus: 'Good',
    guardianName: 'Faly Rasoanaivo',
    guardianContact: '+261 34 245 765',
    address: 'Antananarivo, Madagascar',
    comments: 'Very shy but improving socially',
    lastCheckupDate: '2023-10-11',
  },
  {
    id: '12',
    firstName: 'Haja',
    lastName: 'Raharison',
    birthdate: '2015-05-11',
    enrollmentDate: '2022-09-10',
    gradeLevel: 3,
    healthStatus: 'Moderate',
    guardianName: 'Lala Raharison',
    guardianContact: '+261 34 765 432',
    address: 'Antsirabe, Madagascar',
    comments: 'Prefers quiet activities',
    lastCheckupDate: '2023-08-20',
  },
  {
    id: '13',
    firstName: 'Vonjy',
    lastName: 'Randria',
    birthdate: '2013-10-22',
    enrollmentDate: '2021-09-15',
    gradeLevel: 5,
    healthStatus: 'Good',
    guardianName: 'Soa Randria',
    guardianContact: '+261 32 987 654',
    address: 'Mahajanga, Madagascar',
    comments: 'Enjoys storytelling',
    lastCheckupDate: '2023-09-15',
  },
  {
    id: '14',
    firstName: 'Tahina',
    lastName: 'Ravelomanana',
    birthdate: '2016-01-30',
    enrollmentDate: '2023-01-15',
    gradeLevel: 2,
    healthStatus: 'Underweight',
    guardianName: 'Hery Ravelomanana',
    guardianContact: '+261 34 321 678',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Requires extra nutritional support',
    lastCheckupDate: '2023-10-18',
  },
  {
    id: '15',
    firstName: 'Mamy',
    lastName: 'Rafeno',
    birthdate: '2014-04-25',
    enrollmentDate: '2022-08-20',
    gradeLevel: 4,
    healthStatus: 'Good',
    guardianName: 'Zara Rafeno',
    guardianContact: '+261 34 654 789',
    address: 'Antananarivo, Madagascar',
    comments: 'Good at sports',
    lastCheckupDate: '2023-09-05',
  },
  {
    id: '16',
    firstName: 'Fetra',
    lastName: 'Andrianirina',
    birthdate: '2015-09-14',
    enrollmentDate: '2022-10-05',
    gradeLevel: 3,
    healthStatus: 'Moderate',
    guardianName: 'Bema Andrianirina',
    guardianContact: '+261 33 123 456',
    address: 'Toamasina, Madagascar',
    comments: 'Needs help with reading skills',
    lastCheckupDate: '2023-09-12',
  },
  {
    id: '17',
    firstName: 'Ketaka',
    lastName: 'Rasolonirina',
    birthdate: '2017-11-01',
    enrollmentDate: '2023-04-15',
    gradeLevel: 1,
    healthStatus: 'Good',
    guardianName: 'Sariaka Rasolonirina',
    guardianContact: '+261 34 789 321',
    address: 'Antsirabe, Madagascar',
    comments: 'Very energetic and playful',
    lastCheckupDate: '2023-09-10',
  },
  {
    id: '18',
    firstName: 'Bodo',
    lastName: 'Razanamalala',
    birthdate: '2016-06-25',
    enrollmentDate: '2022-09-30',
    gradeLevel: 2,
    healthStatus: 'Underweight',
    guardianName: 'Fara Razanamalala',
    guardianContact: '+261 33 456 789',
    address: 'Antananarivo, Madagascar',
    comments: 'Requires frequent checkups',
    lastCheckupDate: '2023-08-15',
  },
  {
    id: '19',
    firstName: 'Zo',
    lastName: 'Ramaroson',
    birthdate: '2014-03-12',
    enrollmentDate: '2021-09-01',
    gradeLevel: 4,
    healthStatus: 'Good',
    guardianName: 'Hanta Ramaroson',
    guardianContact: '+261 34 321 987',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Good at group activities',
    lastCheckupDate: '2023-10-22',
  },
  {
    id: '20',
    firstName: 'Jean',
    lastName: 'Rafenoarivelo',
    birthdate: '2013-07-04',
    enrollmentDate: '2021-08-12',
    gradeLevel: 5,
    healthStatus: 'Moderate',
    guardianName: 'Norosoa Rafenoarivelo',
    guardianContact: '+261 32 456 123',
    address: 'Antsiranana, Madagascar',
    comments: 'Excels in math',
    lastCheckupDate: '2023-09-28',
  },
  {
    id: '21',
    firstName: 'Fara',
    lastName: 'Rajaonarivelo',
    birthdate: '2016-12-20',
    enrollmentDate: '2023-03-05',
    gradeLevel: 2,
    healthStatus: 'Good',
    guardianName: 'Lanto Rajaonarivelo',
    guardianContact: '+261 34 235 789',
    address: 'Toamasina, Madagascar',
    comments: 'Shows leadership qualities',
    lastCheckupDate: '2023-10-10',
  },
  {
    id: '22',
    firstName: 'Lova',
    lastName: 'Ratsimbazafy',
    birthdate: '2014-09-02',
    enrollmentDate: '2022-11-01',
    gradeLevel: 4,
    healthStatus: 'Moderate',
    guardianName: 'Mamy Ratsimbazafy',
    guardianContact: '+261 34 654 123',
    address: 'Antananarivo, Madagascar',
    comments: 'Shows interest in science',
    lastCheckupDate: '2023-08-15',
  },
  {
    id: '23',
    firstName: 'Faniry',
    lastName: 'Razafindrabe',
    birthdate: '2017-04-18',
    enrollmentDate: '2023-02-20',
    gradeLevel: 1,
    healthStatus: 'Underweight',
    guardianName: 'Tiana Razafindrabe',
    guardianContact: '+261 34 987 654',
    address: 'Mahajanga, Madagascar',
    comments: 'Requires extra nutritional support',
    lastCheckupDate: '2023-10-05',
  },
  {
    id: '24',
    firstName: 'Nirina',
    lastName: 'Razanabo',
    birthdate: '2015-02-15',
    enrollmentDate: '2022-08-10',
    gradeLevel: 3,
    healthStatus: 'Good',
    guardianName: 'Tsiry Razanabo',
    guardianContact: '+261 34 123 987',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Very creative in art',
    lastCheckupDate: '2023-09-17',
  },
  {
    id: '25',
    firstName: 'Mahery',
    lastName: 'Randriamampionona',
    birthdate: '2013-10-30',
    enrollmentDate: '2021-10-25',
    gradeLevel: 5,
    healthStatus: 'Moderate',
    guardianName: 'Arisoa Randriamampionona',
    guardianContact: '+261 34 765 210',
    address: 'Antsirabe, Madagascar',
    comments: 'Needs encouragement in reading',
    lastCheckupDate: '2023-09-02',
  },
  {
    id: '26',
    firstName: 'Ihaja',
    lastName: 'Rasolondraibe',
    birthdate: '2015-11-14',
    enrollmentDate: '2022-07-30',
    gradeLevel: 3,
    healthStatus: 'Good',
    guardianName: 'Ny Rado Rasolondraibe',
    guardianContact: '+261 32 658 951',
    address: 'Antananarivo, Madagascar',
    comments: 'Great at problem-solving',
    lastCheckupDate: '2023-09-24',
  },
  {
    id: '27',
    firstName: 'Santatra',
    lastName: 'Razanamalala',
    birthdate: '2017-07-12',
    enrollmentDate: '2023-05-10',
    gradeLevel: 1,
    healthStatus: 'Underweight',
    guardianName: 'Lova Razanamalala',
    guardianContact: '+261 34 798 654',
    address: 'Antsirabe, Madagascar',
    comments: 'Enjoys singing in groups',
    lastCheckupDate: '2023-09-28',
  },
  {
    id: '28',
    firstName: 'Soa',
    lastName: 'Rafaralahy',
    birthdate: '2014-06-08',
    enrollmentDate: '2022-06-15',
    gradeLevel: 4,
    healthStatus: 'Good',
    guardianName: 'Zo Rafaralahy',
    guardianContact: '+261 34 521 789',
    address: 'Antananarivo, Madagascar',
    comments: 'Quick to make friends',
    lastCheckupDate: '2023-08-21',
  },
  {
    id: '29',
    firstName: 'Hanitra',
    lastName: 'Rajoelina',
    birthdate: '2015-05-03',
    enrollmentDate: '2022-08-08',
    gradeLevel: 3,
    healthStatus: 'Moderate',
    guardianName: 'Tina Rajoelina',
    guardianContact: '+261 34 456 789',
    address: 'Toamasina, Madagascar',
    comments: 'Loves participating in class',
    lastCheckupDate: '2023-09-16',
  },
  {
    id: '30',
    firstName: 'Lahatra',
    lastName: 'Randriamanana',
    birthdate: '2013-03-19',
    enrollmentDate: '2021-09-22',
    gradeLevel: 5,
    healthStatus: 'Good',
    guardianName: 'Faly Randriamanana',
    guardianContact: '+261 34 654 321',
    address: 'Antananarivo, Madagascar',
    comments: 'Excels in group discussions',
    lastCheckupDate: '2023-10-10',
  },
  {
    id: '31',
    firstName: 'Tahina',
    lastName: 'Andriamasinoro',
    birthdate: '2016-11-07',
    enrollmentDate: '2023-03-12',
    gradeLevel: 2,
    healthStatus: 'Moderate',
    guardianName: 'Aina Andriamasinoro',
    guardianContact: '+261 34 213 456',
    address: 'Toamasina, Madagascar',
    comments: 'Quick learner, especially in math',
    lastCheckupDate: '2023-10-01',
  },
  {
    id: '32',
    firstName: 'Zo',
    lastName: 'Razanajatovo',
    birthdate: '2015-01-25',
    enrollmentDate: '2022-05-18',
    gradeLevel: 3,
    healthStatus: 'Good',
    guardianName: 'Hery Razanajatovo',
    guardianContact: '+261 34 654 987',
    address: 'Antananarivo, Madagascar',
    comments: 'Always helping classmates',
    lastCheckupDate: '2023-09-10',
  },
  {
    id: '33',
    firstName: 'Samy',
    lastName: 'Rajoarihaona',
    birthdate: '2014-12-03',
    enrollmentDate: '2022-11-03',
    gradeLevel: 4,
    healthStatus: 'Good',
    guardianName: 'Noeline Rajoarihaona',
    guardianContact: '+261 32 678 234',
    address: 'Antsirabe, Madagascar',
    comments: 'Excellent in science projects',
    lastCheckupDate: '2023-08-22',
  },
  {
    id: '34',
    firstName: 'Nomena',
    lastName: 'Rakotoarivony',
    birthdate: '2017-09-15',
    enrollmentDate: '2023-06-22',
    gradeLevel: 1,
    healthStatus: 'Underweight',
    guardianName: 'Tolotra Rakotoarivony',
    guardianContact: '+261 34 123 456',
    address: 'Mahajanga, Madagascar',
    comments: 'Shows a keen interest in reading',
    lastCheckupDate: '2023-09-30',
  },
  {
    id: '35',
    firstName: 'Ny Hasina',
    lastName: 'Andriamanjato',
    birthdate: '2013-08-11',
    enrollmentDate: '2021-12-05',
    gradeLevel: 5,
    healthStatus: 'Moderate',
    guardianName: 'Lalasoa Andriamanjato',
    guardianContact: '+261 34 654 123',
    address: 'Antananarivo, Madagascar',
    comments: 'Enthusiastic about sports',
    lastCheckupDate: '2023-09-21',
  },
  {
    id: '36',
    firstName: 'Volana',
    lastName: 'Rakotondrazaka',
    birthdate: '2015-02-18',
    enrollmentDate: '2022-04-15',
    gradeLevel: 3,
    healthStatus: 'Good',
    guardianName: 'Rina Rakotondrazaka',
    guardianContact: '+261 34 876 543',
    address: 'Toamasina, Madagascar',
    comments: 'Very creative in drawing',
    lastCheckupDate: '2023-09-13',
  },
  {
    id: '37',
    firstName: 'Toky',
    lastName: 'Rabenjamina',
    birthdate: '2016-03-29',
    enrollmentDate: '2023-01-15',
    gradeLevel: 2,
    healthStatus: 'Good',
    guardianName: 'Mbolatiana Rabenjamina',
    guardianContact: '+261 34 987 123',
    address: 'Antsirabe, Madagascar',
    comments: 'Good participation in class',
    lastCheckupDate: '2023-10-04',
  },
  {
    id: '38',
    firstName: 'Rindra',
    lastName: 'Andriamampianina',
    birthdate: '2014-11-05',
    enrollmentDate: '2022-10-20',
    gradeLevel: 4,
    healthStatus: 'Moderate',
    guardianName: 'Tefy Andriamampianina',
    guardianContact: '+261 34 654 789',
    address: 'Mahajanga, Madagascar',
    comments: 'Requires extra help in math',
    lastCheckupDate: '2023-08-29',
  },
  {
    id: '39',
    firstName: 'Tahiry',
    lastName: 'Razanamparany',
    birthdate: '2013-06-21',
    enrollmentDate: '2021-08-15',
    gradeLevel: 5,
    healthStatus: 'Good',
    guardianName: 'Sitraka Razanamparany',
    guardianContact: '+261 32 456 123',
    address: 'Antananarivo, Madagascar',
    comments: 'High achiever, aims to excel',
    lastCheckupDate: '2023-09-12',
  },
  {
    id: '40',
    firstName: 'Felana',
    lastName: 'Ravalomanana',
    birthdate: '2017-01-07',
    enrollmentDate: '2023-07-15',
    gradeLevel: 1,
    healthStatus: 'Underweight',
    guardianName: 'Fanilo Ravalomanana',
    guardianContact: '+261 34 321 654',
    address: 'Fianarantsoa, Madagascar',
    comments: 'Enjoys storytime sessions',
    lastCheckupDate: '2023-09-26',
  },
]
